#!/usr/bin/env python3
"""Derive the pipeline's thresholds from measured distributions.

  ./calibrate.py

Writes thresholds.json for build_cycles.py, and calibration.md showing the
histograms each number came from -- so a later reader can see why 4 seconds
and not 10.

The load-bearing question this answers is whether pause lengths separate into
"still working" and "stopped to look". If the distribution is unimodal, the
systematic pole has no anchor and the axis has to rest on burst composition
alone. calibration.md reports that shape explicitly rather than burying it.
"""
import json
import os
import statistics

import lib

# A burst gap below the coalescing window would split one gesture in two.
MIN_BURST_GAP_S = 2.0
GAP_EDGES = [0, 1, 2, 3, 5, 8, 13, 21, 34, 60, 120, 300, 900]


def histogram(values, edges):
    """Count values into len(edges)-1 bins; anything past the last edge goes
    into the final bin rather than being dropped."""
    counts = [0] * (len(edges) - 1)
    for v in values:
        placed = False
        for i in range(len(edges) - 1):
            if edges[i] <= v < edges[i + 1]:
                counts[i] += 1
                placed = True
                break
        if not placed and v >= edges[-1]:
            counts[-1] += 1
    return counts


def choose_burst_gap(gaps):
    """The p90 of observed inter-operation gaps, floored at the coalescing
    window. Most consecutive operations inside real work are close together;
    the p90 is where the tail of deliberate pauses begins."""
    if not gaps:
        return MIN_BURST_GAP_S
    ordered = sorted(gaps)
    idx = max(0, min(len(ordered) - 1, int(0.90 * len(ordered)) - 1))
    p90 = ordered[idx]
    return max(MIN_BURST_GAP_S, float(p90))


def _gaps_between_operations(edits):
    rows = lib.query("""
        SELECT date_diff('millisecond', prev_ended, started) / 1000.0 AS gap_s
        FROM (
          SELECT started,
                 lag(ended) OVER (PARTITION BY doc_id, tile_id ORDER BY started) AS prev_ended
          FROM read_parquet('%s')
          WHERE class IN ('structure', 'parameter')
            AND NOT clock_suspect
        )
        WHERE prev_ended IS NOT NULL
          AND date_diff('millisecond', prev_ended, started) BETWEEN 0 AND 3600000
    """ % edits)
    return [r["gap_s"] for r in rows]


def _md_table(title, edges, counts):
    total = sum(counts) or 1
    lines = ["### %s" % title, "", "| range (s) | count | share |", "|---|---|---|"]
    for i, n in enumerate(counts):
        lines.append("| %g–%g | %d | %.1f%% |" % (edges[i], edges[i + 1], n,
                                                  100.0 * n / total))
    lines.append("")
    return lines


def main():
    derived = lib.ensure_derived()
    edits = os.path.join(derived, "edits.parquet")
    lib.require_file(edits)

    gaps = _gaps_between_operations(edits)
    burst_gap = choose_burst_gap(gaps)

    # Pauses are gaps longer than the burst gap. Their shape decides whether
    # the systematic pole is detectable at all.
    pauses = [g for g in gaps if g > burst_gap]
    counts = histogram(gaps, GAP_EDGES)

    thresholds = {
        "burst_gap_s": round(burst_gap, 2),
        # A watch has to outlast the burst gap, and stop before it becomes a
        # class transition. Both ends are re-checked against the histogram
        # below; they are starting points, not conclusions.
        "watch_min_s": round(burst_gap, 2),
        "watch_max_s": 300.0,
        "ui_staleness_s": 120.0,
        "generated_from": {
            "operation_gaps": len(gaps),
            "pauses": len(pauses),
            "median_gap_s": round(statistics.median(gaps), 2) if gaps else None,
            "median_pause_s": round(statistics.median(pauses), 2) if pauses else None,
        },
    }

    with open(os.path.join(derived, "thresholds.json"), "w") as handle:
        json.dump(thresholds, handle, indent=2)

    lines = ["# Calibration", "",
             "Generated by `calibrate.py`. These histograms are why the "
             "thresholds are what they are.", "",
             "Operations counted: `structure` and `parameter` only, on "
             "documents that are not clock-suspect.", ""]
    lines += _md_table("Gaps between consecutive operations", GAP_EDGES, counts)
    lines += ["### Chosen thresholds", "", "```json",
              json.dumps(thresholds, indent=2), "```", "",
              "### The open risk", "",
              "If the histogram above is smooth and unimodal, pause length "
              "does not separate 'still working' from 'stopped to look', and "
              "the systematic pole has no anchor. Read the shape before "
              "trusting any candidate the pipeline emits.", ""]
    with open(os.path.join(derived, "calibration.md"), "w") as handle:
        handle.write("\n".join(lines))

    print("burst_gap_s=%.2f  watch=%.2f–%.0fs  (from %d gaps, %d pauses)"
          % (thresholds["burst_gap_s"], thresholds["watch_min_s"],
             thresholds["watch_max_s"], len(gaps), len(pauses)))
    print("wrote thresholds.json and calibration.md")


if __name__ == "__main__":
    main()
